### ISSUE TITLE
Is there a way to fetch test cases ?

### ISSUE THREAD

**Issue by fahimfaisal42** [xeluxee/competitest.nvim#1]
Some problems have a lot of test cases so making them will take a lot of time. So, if there could be some sort of integration between this plugin and extensions like Competitive Companion it would be the best plugin for cp.

also thanks for this cool plugin.

**Comment by xeluxee** [comment]
I'm planning to add integration with competitive companion
See https://github.com/xeluxee/competitest.nvim#future-plans

**Comment by p00f** [comment]
@xeluxee  you can take a look at my plugin ([cphelper.nvim](https://github.com/p00f/cphelper.nvim), specifically https://github.com/p00f/cphelper.nvim/blob/main/lua/cphelper/prepare.lua and https://github.com/p00f/cphelper.nvim/blob/main/lua/cphelper/prepare.lua.

If competitest gets this feature I'll probably stop maintaining cphelper

**Comment by xeluxee** [comment]
@p00f thanks for your suggestion, I'll give a look. Also thanks for developing cphelper, a plugin from which I took inspiration to create competitest 

At the moment I'm working on another feature (storing testcases in a single file)
Soon I'll start working on fetching testcases

**Comment by xeluxee** [comment]
@fahimfaisal42 @p00f I've just implemented this feature in b9a59ae8260a9d7337cffea5d986afd5f9593b41

Let me know if everything works fine before closing this issue

**Comment by p00f** [comment]
Works great, thanks

**Comment by krishnakumarg1984** [comment]
@p00f Do you plan to stop developing `cphelper.nvim`?

**Comment by p00f** [comment]
Not for now 😄

**Comment by krishnakumarg1984** [comment]
It would be nice if these two plugins could document the differences with respect to the other. This shall aid the user to make an informed choice about which to install. E.g, see [this example](https://github.com/Darazaki/indent-o-matic/issues/12) for detailed comments by both plugin authors comparing indent-o-matic and guessindent.nvim 

Also, do the plugins work with leetcode?

**Comment by krishnakumarg1984** [comment]
@p00f Ok. Understood. May I please request mentioning in your README.md, the CP websites the plugin can work with?

**Comment by p00f** [comment]
It uses https://github.com/jmerle/competitive-companion and should work with whatever the browser extension supports

**Comment by has12zen** [comment]
So i installed it but it is not working with my neovim. I am trying to use the companion extension but it is not able to get the question.
