### ISSUE TITLE
Intermediate empty line should be included in the comparison between expected and actual ouput

### ISSUE THREAD

**Issue by MuhammadSawalhy** [xeluxee/competitest.nvim#12]
Example of problems that required blank lines: https://onlinejudge.org/index.php?option=onlinejudge&Itemid=99999999&page=show_problem&category=0&problem=349&mosmsg=Submission+received+with+ID+27577557

> After each output test set, your program should print exactly one blank line.

But here we get another issue! Is it right to include the trailing empty lines at the end of the output in the comparison?

![image](https://user-images.githubusercontent.com/42011920/174336847-99dead46-8fa9-4edd-99da-32e130c01690.png)

**Comment by xeluxee** [comment]
See `output_compare_method` in [configuration](https://github.com/xeluxee/competitest.nvim#configuration). Setting it to `exact` could solve your problem.

**Comment by MuhammadSawalhy** [comment]
> See `output_compare_method` in [configuration](https://github.com/xeluxee/competitest.nvim#configuration). Setting it to `exact` could solve your problem.

Oh I didn't know about this option, sorry for my rush in making issues.
