### ISSUE TITLE
Issue with nui

### ISSUE THREAD

**Issue by MuhammadSawalhy** [xeluxee/competitest.nvim#14]
## Versions

1. NeoVim: v0.7.2
2. compitest: c86a94c - latest
3. nui.nvim: [62facd3](https://github.com/MunifTanjim/nui.nvim/commit/62facd37e0dd8196212399a897374f689886f500) - latest

## Error message

![image](https://user-images.githubusercontent.com/42011920/188279467-64ebbab0-3613-4739-84c4-a0ab394bcdb4.png)

## Reproducible steps

1. `:CompiTestRun`
4. <kbd>e</kbd>
5. <kbd>q</kbd>
6. `:CompiTestRun`

**Comment by xeluxee** [comment]
This behaviour is probably caused by a recent `nui.nvim` update. I'll look into it

**Comment by xeluxee** [comment]
Fixed thanks to `nui.nvim` author, @MunifTanjim
For further details see https://github.com/MunifTanjim/nui.nvim/issues/190

@MuhammadSawalhy just update `nui.nvim`

**Comment by MuhammadSawalhy** [comment]
Thanks
