### ISSUE TITLE
feat: filtering output before comparing.

### ISSUE THREAD

**Issue by shadmansaleh** [xeluxee/competitest.nvim#15]
Are you interested in exposing a filter function in config that is applied on output before comparing it to check if it's matches with the desired one or not?

I have a debugging function that always prints lines starting with "DBG )>".  If competitest compares the output with these removed I can observe the debug output while also check if the test is passing.

I can currently achieve it by injecting a custom compare method like this.
```lua
local compare_methods = require('competitest.compare').methods
function compare_methods.filter_squish(output, expout)
  local strs = {}
  for str in vim.gsplit(output, '\n') do
    if not vim.startswith(str, 'DBG )>') then
      table.insert(strs, str)
    end
  end
  return compare_methods.squish(table.concat(strs, '\n'), expout)
end

require('competitest').setup {
  output_compare_method = 'filter_squish',
}
```

But it's kind of hacky. So I think it'd be nice If competitest allows me to provide a filter function is config.

**Comment by xeluxee** [comment]
Why not printing debug statements on `stderr`?

**Comment by shadmansaleh** [comment]
> Why not printing debug statements on stderr?

On tests that contain multiple cases. It's easier to understand which debug output is from which case.

**Comment by shadmansaleh** [comment]
You should have just told me `output_compare_method` can be a function.

>custom function: you can use a function accepting two arguments, two strings representing output and expected output. It should return true if the given output is acceptable, false otherwise. Example:
>```lua
>require('competitest').setup {
> 	output_compare_method = function(output, expected_output)
> 		if output == expected_output then
> 			return true
> 		else
> 			return false
> 		end
> 	end
> }
>```
