### ISSUE TITLE
Auto Recieve the whole contest

### ISSUE THREAD

**Issue by smarttommyau** [xeluxee/competitest.nvim#18]
Recieve the whole contest, for the other problems.It should auto open a file on the buffer and with the task name. 
This can be implement by keep recieving data and only close when no data is transmit for an amount of time.
This would be really useful and can bring huge convenience.

**Comment by xeluxee** [comment]
I'm already working on cloning testcases and fixing #5.
But this task needs a bit of refactoring, so don't expect this feature to be implemented immediately

**Comment by smarttommyau** [comment]
I see. Thanks for your great efforts

**Comment by xeluxee** [comment]
This feature has just been implemented in 741f4c053a3749a1fab3bcbce14dd6082950cf75
See https://github.com/xeluxee/competitest.nvim#receive-testcases-problems-and-contests
