### ISSUE TITLE
Unable to switch popup windows using ctrl(H,J,K,L)

### ISSUE THREAD

**Issue by akashdiphazra** [xeluxee/competitest.nvim#20]

**Comment by xeluxee** [comment]
This isn't my fault, Neovim isn't able to handle `<C-w>h,j,k,l` with floating windows.
You can use `<C-w><C-w>` or press `i`, `o`, `a`, `e` to view input, output, expected output and stderr in a bigger window.

**Comment by akashdiphazra** [comment]
Ok !!
