### ISSUE TITLE
Is there a way to make it always replace the exisitng test cases without asking for a prompt?

### ISSUE THREAD

**Issue by vijay-72** [xeluxee/competitest.nvim#22]
I use the same file for all problems in a contest, so every time I receive testcases, it asks to either replace all (or) add the new test cases. Is there any way to set an option or something to make it always replace all testcases? Thanks!

![image](https://user-images.githubusercontent.com/103360527/210074162-0e4caded-a0fb-44ff-9759-e047356e158c.png)

**Comment by xeluxee** [comment]
Currently there isn't a way to skip confirm message. I'll add an option to do that.

**Comment by xeluxee** [comment]
Closing with 9aaf282.
@vijay-72 set `replace_received_testcases` to true.
