### ISSUE TITLE
feat: Create testcases_directory if it doesn't exist

### ISSUE THREAD

**Issue by shadmansaleh** [xeluxee/competitest.nvim#3]
Currently if `testcases_directory` doesn't already exists competitest fails to save tests . This directory should be created if it doesn't exist . I think `compile_directory` & `run_directory` also faces similar issue though I haven't tried .

**Comment by shadmansaleh** [comment]
On a side note since `writting vimdoc` is in your [future planes](https://github.com/xeluxee/competitest.nvim#future-plans) . You could just convert README.md to vimdoc with [panvimdoc](https://github.com/kdheepak/panvimdoc) . You can just through in a CI for the conversion like we do in [lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/.github/workflows/autogen.yml)

**Comment by xeluxee** [comment]
> Currently if `testcases_directory` doesn't already exists competitest fails to save tests . This directory should be created if it doesn't exist . I think `compile_directory` & `run_directory` also faces similar issue though I haven't tried .

You're right, I'll fix it

**Comment by xeluxee** [comment]
> On a side note since `writting vimdoc` is in your [future planes](https://github.com/xeluxee/competitest.nvim#future-plans) . You could convert README.md to vimdoc with [panvimdoc](https://github.com/kdheepak/panvimdoc) . You can just through in a CI for the conversion like we do in [lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/.github/workflows/autogen.yml)

Thanks, I'll give a look

**Comment by xeluxee** [comment]
Fixed with 491b7cc

**Comment by shadmansaleh** [comment]
Thanks . It works now :)
