### ISSUE TITLE
Fails to get problem or contest when there is a question mark.

### ISSUE THREAD

**Issue by aniketpriyadarshi00** [xeluxee/competitest.nvim#31]
I was giving a contest on codeforces. The first problem had a question mark in it. I did CompetiTestReceive contest and then I pressed I pressed the green button on my browser but as soon as it reached to neovim there occured an error because the first problem had a question mark in it. I would highly request you to just remove characters which cause this problem.

Steps to reproduce:

1. Go to https://codeforces.com/contest/1800 on browser.
2. Parse the contest.
3. Look back at neovim and receive an error.

**Comment by xeluxee** [comment]
Cannot reproduce your issue with provided steps.
What command have you launched? Please paste the error you're getting

**Comment by aniketpriyadarshi00** [comment]
Its on windows.

**Comment by aniketpriyadarshi00** [comment]
![image](https://user-images.githubusercontent.com/77151836/223312835-a2063d73-5e6e-4b52-ab43-30c742025ddb.png)

**Comment by xeluxee** [comment]
Please try `windows-illegal-characters` branch

**Comment by xeluxee** [comment]
Fixed with 87c1d75
