### ISSUE TITLE
Could not get the directory name to be of the 

### ISSUE THREAD

**Issue by vishalpaudel** [xeluxee/competitest.nvim#32]
I am a neovim and lua fan. I do not know much configuration and so I failed to change the directory name on receive to the name of the judge + contest + problem:

**CodeForces/CodeforcesRound858(Div2)/AWalkingMaster/**

The following package(very similar in fact) has a very neat foldering mechanism which does this:

https://github.com/p00f/cphelper.nvim/tree/main

Please add something like this to the competitest plugin?

**Comment by xeluxee** [comment]
Right now you can clone a contest with `:CompetiTestReceive contest` and choose folder name manually.
Currently we are planning to introduce some options to customize folders naming for received problems and contests, see #28.

**Comment by xeluxee** [comment]
Closing with #40
See how to [customize folder structure](https://github.com/xeluxee/competitest.nvim/tree/master#customize-folder-structure) for received problems and contests.
