### ISSUE TITLE
Rerun makes no sense if the program is not recompiled

### ISSUE THREAD

**Issue by TroySigX** [xeluxee/competitest.nvim#35]
For re-running a test, the only scenario I can think of is that when someone modifies their program, opens `Competitest` (using `:CompetitestRunNE`) and runs that specific test case. So I dont think it really makes sense to re-run a test without recompiling the program

**Comment by xeluxee** [comment]
The command `:CompetiTestRunNE` only opens competitest UI if it was previously closed, but it doesn't compile or run testcases.

To re-run without recompiling you should launch `:CompetiTestRunNC`. It makes sense in the following scenarios:
1. If source code is pretty big compilation becomes slow
2. If current testcases aren't enough to test a solution in depth and program is already compiled, other testcases can be added and tested without recompiling
3. Solutions making use of random values or nondeterministic algorithms

**Comment by TroySigX** [comment]
What I meant was that, using the R (or Ctrl-R) mapping in the pop up to re run a test doesnt really make sense

**Comment by xeluxee** [comment]
> What I meant was that, using the R (or Ctrl-R) mapping in the pop up to re run a test doesnt really make sense since normally, people have actually modified the program and want to rerun that specific test for debug purposes

I know, that's an uncommon use-case, but scenario 3 still holds and there's a fourth one: re-running a testcase after it's killed by user or by a signal

**Comment by TroySigX** [comment]
How about adding another mapping `r` (lowercase) for the functionality?

**Comment by xeluxee** [comment]
> How about adding another mapping `r` (lowercase) for the functionality?

You can customize mappings in setup, see `runner_ui.mappings.run_again` and `runner_ui.mappings.run_all_again`

**Comment by TroySigX** [comment]
How do I call recompile in runner UI, I dont see any available command

**Comment by TroySigX** [comment]
I tried to setup a mapping like this:
``` lua
local map = vim.keymap.set
map('n', '<space>tr', function()
  require('competitest.commands').run_testcases("", true, true)
end)
```
But from your [code](https://github.com/xeluxee/competitest.nvim/blob/master/lua/competitest/commands.lua), it seems that if `only_show` is true, then the `compile` argument will be completely ignored.

**Comment by xeluxee** [comment]
> Here's what I thank, for the current `CompetiTestRunNE`, it should be renamed to `CompetiTestOpen` (or `CompetiTestToggleUI`) because the original name might be confusing for some users, like me (I previously thought that `CompetiTestRunNE` recompiles the program but just not run the tests). And create a new command `CompetiTestRunNE` which compiles the program, but not run the tests

Renaming to `CompetiTestToggleUI` would make it clearer. Though, as [someone suggested](https://github.com/xeluxee/competitest.nvim/issues/6#issue-1268649140), I'm planning to substitute current commands with neovim-style commands, such as `:CompetiTest run` and `:CompetiTest toggle_ui`.

Regarding a command that only compiles a program without running tests, I think it'd be outside CompetiTest's scope, since its main feature is testing testcases. There are [many plugins](https://github.com/rockerBOO/awesome-neovim#code-runner) out there to compile a source file.
Anyway you can press `R` with cursor on `COMPILE` line to compile again.

**Comment by TroySigX** [comment]
Thanks @xeluxee ! That works great for me.
