### ISSUE TITLE
unable to recieve test case

### ISSUE THREAD

**Issue by gaurav-palariya** [xeluxee/competitest.nvim#36]
how to receive test cases, when i run :competireceive, it say argument required ..please help

**Comment by xeluxee** [comment]
As `README.md` [states](https://github.com/xeluxee/competitest.nvim#receive-testcases-problems-and-contests), the command `:CompetiTestReceive` requires an argument

- Download only testcases with `:CompetiTestReceive testcases`
- Download a problem with `:CompetiTestReceive problem` (source file is automatically created along with testcases)
- Download an entire contest with `:CompetiTestReceive contest` (make sure to be on the homepage of the contest, not of a single problem)
