### ISSUE TITLE
Commands Are Not Found!!!

### ISSUE THREAD

**Issue by SHAHNUR00** [xeluxee/competitest.nvim#38]
Add, Edit, Delete Command are not showing when I install them with vim-plug!!!!!!!!!!

**Comment by xeluxee** [comment]
Please be more exhaustive, what kind of error are you getting? Did you run `:PlugInstall`? Did you call CompetiTest setup in your config?

And please use a meaningful title when opening an issue.

**Comment by SHAHNUR00** [comment]
So I installed competitest.nvim using plug. I ran `: PlugInstall `and it installed all the necessary files without any error. But when I searched for the commands( `:CompetiTestAdd`, `:CompetiEdit`, `:CompetiDelete` ) then no preview or option was shown unfortunately at the bottom of the Neovim.

**Comment by xeluxee** [comment]
Did you call CompetiTest [setup](https://github.com/xeluxee/competitest.nvim#usage) in your config?

**Comment by SHAHNUR00** [comment]
Actually I use vimscript. The setup function is for Lua. Unfortunately I never use lua. If you could help further, I'll be glad.

**Comment by xeluxee** [comment]
> Actually I use vimscript. The setup function is for Lua.

To configure Neovim you can use vimscript and lua  at the same time. To use lua inside vimscript you can use lua heredoc block (see `:h lua-guide-using-Lua`):
``` vim
lua << EOF
  require('competitest').setup()
EOF
```

If you're using newer Neovim plugins I suggest you to switch to lua config, since many of them are configured through a lua setup function.

**Comment by SHAHNUR00** [comment]
Thank You.

**Comment by tkhoi123** [comment]
![image](https://github.com/xeluxee/competitest.nvim/assets/105137932/14fa4a1d-ecce-4f38-a4d5-37e19d3d73d2)
I has same problem but i receive error when put
`lua << EOF
  require('competitest').setup()
EOF`
in init.vim:
`lcall plug#begin('~/AppData/Local/nvim/plugged')
    Plug 'MunifTanjim/nui.nvim'        " it's a dependency
    Plug 'xeluxee/competitest.nvim'
    let g:airline_theme='onedark'
lua << EOF
  require('competitest').setup()
EOF
call plug#end()
`
How to fix it
