### ISSUE TITLE
Tests are not run when a dot `.` is in the file name

### ISSUE THREAD

**Issue by MuhammadSawalhy** [xeluxee/competitest.nvim#4]
I guess that the problem that the code is only compiled with no test cases detected is due to the presence of a dot in the file name, `A.Vanya-and-Fence.cpp`. But when I changed the name to `A.Vanya-and-Fence/main.cpp`, tests are run successfully ❤️.

Note that `:CompetiConvert auto` also says no test cases detect even that they are already there and generated using `:CompetiRecieve`

https://codeforces.com/contest/677/problem/A

**Comment by xeluxee** [comment]
Thanks for reporting this issue
This is caused by lua string functions interpreting dots and dashes as pattern special characters, so I have to find a way to escape all the characters that could mess up lua patterns system. I'll try to fix it asap.

Anyway in the meantime you can set `testcases_use_single_file` to true, since this storage method isn't affected by this issue

**Comment by MuhammadSawalhy** [comment]
I think the priority goes for "submitting" the code feature first. But, I think this issue won't take that much time to worry about priority. I may work on the submission feature and create a PR for it. But that won't be before three weeks or maybe more from now as I have no free time meanwhile.

**Comment by xeluxee** [comment]
Before working on "submit" feature we have to choose the right tool to submit.
And since this is _only_ a bugfix it could take me a shorter time than implementing a new feature.

I won't be available too in a short time to work on implementing new features, anyway any help would be appreciated

**Comment by xeluxee** [comment]
@MuhammadSawalhy after d8a02afa196c2b6739255bb0f36c1ff602f853a6 it should be fixed

**Comment by MuhammadSawalhy** [comment]
> after https://github.com/xeluxee/competitest.nvim/commit/d8a02afa196c2b6739255bb0f36c1ff602f853a6 it should be fixed

Well done! Fixed ❤️
