### ISSUE TITLE
CompetiTest receive only gets 1 testcase.

### ISSUE THREAD

**Issue by fg-charles** [xeluxee/competitest.nvim#46]
When trying to receive a problem using `CompetiTest recieve problem` and using the Competitive Companion on the problem, I only ever receive a single test case.

I've tried this on Codeforces and Codechef. I've also tried the plugin cphelper and the same issue happens there. 

I think this is an issue with Competitive Companions. I think it's parsing the problem page and only getting the example testcase, which is usually singular. For example when trying it with this problem: https://codeforces.com/problemset/problem/4/A
The only test-case recieved is the example testcase.

How would I get all the testcases?

**Comment by xeluxee** [comment]
> For example when trying it with this problem: https://codeforces.com/problemset/problem/4/A
The only test-case recieved is the example testcase.

Indeed, that's exactly what Competitive Companion does, because it can only access example testcases.

You can't get all the testcases because on most competitive programming platforms they're private.
