### ISSUE TITLE
[Feature Request] read all testcases in the testcase directory

### ISSUE THREAD

**Issue by stegatxins0** [xeluxee/competitest.nvim#49]
Sometimes the problem provide attachment such as `sample_01.in` and `eg_02.in`. It is quite a hassle to manually rename the files to the format as configured in `testcases_single_file_format`. Is it possible to configure competitest.nvim such that it reads all files that ends with a certain extension such as `.in` in the testcase directory?

**Comment by xeluxee** [comment]
Sorry but this is out of scope.
As a workaround you can make a little script to rename all files ending with `.in` to `'number'.in`, then set `testcases_input_file_format = "$(TCNUM).in"`.
