### ISSUE TITLE
[#feature] Importing the name of the problem along with testcase

### ISSUE THREAD

**Issue by Ram5anthosh** [xeluxee/competitest.nvim#5]
i am trying to import the name of the problem along with the test cases before solving once in for all, as it will reduce the cumbersome process of naming the problem each time. If we could also create the file using a pre selected template it will be good.

I have seen another competitve programming plugin doing this and this could be a valuable addition for people who want to solve the problems on the go. #feature

**Comment by xeluxee** [comment]
> i am trying to import the name of the problem along with the test cases before solving once in for all

What do you mean exactly? Are you talking about testcases fetching? Or testcases creation?
You can create a file (e.g. `file.cpp`) and then use `:CompetiTestAdd` to add testcases.

> I have seen another competitve programming plugin doing this

What plugin are you talking about?

**Comment by Ram5anthosh** [comment]
> What plugin are you talking about?

[Competitive Programming Helper (cph)](https://marketplace.visualstudio.com/items?itemName=DivyanshuAgrawal.competitive-programming-helper) in vs code, this plugin not only gets the test cases but also the name of the problem like A_Games.cpp or D_Flip_the_Bits.cpp. This plugin can be accessed from [this](https://github.com/agrawal-d/cph) repository. 

A video explaining the working of the plugin if [here](https://www.youtube.com/watch?v=ZM1USzeDwc8). This could be a great addition to the current features being offered by the plugin as even naming the file will be automated.

I am not sure if the above mentioned task is easy to implement. But as stated above it could be a great addition to the already wonderful plugin.

**Comment by xeluxee** [comment]
This feature has just been implemented in 741f4c053a3749a1fab3bcbce14dd6082950cf75
See https://github.com/xeluxee/competitest.nvim#receive-testcases-problems-and-contests
