### ISSUE TITLE
Some idea concerning new features

### ISSUE THREAD

**Issue by XXiaoA** [xeluxee/competitest.nvim#51]
Fist of all, I really appreciate this awesome plugin, which do me a big favour. After using it for a while, I have the following ideas to make it better:
- merge three command about testcases into one command (like `testcases` simply). And we can add, edit, remove testcases with our keybinding.
- change the color of popup window's boarder (except Testcases window) by the test result, so as to recognise the result at glance. For example, red for wrong test and green for correct one.
- add something like `hook` or `user event` . For instance, i can create `build` directory before running code to put the binary file into build directory  then.

**Comment by XXiaoA** [comment]
>This looks like a niche use-case

Indeed, after thinking twice, it is not necessary.

>You can already to that

Thanks, it works. But I think maybe `user event` is still a useful function. With it, we can format the code before running, sent notification after finishing the tests etc. ( though i dont need them) It will make the plugin more customizable. What's your opinion? I am not pretty sure if it should be added to.

**Comment by xeluxee** [comment]
> we can format the code before running

By default `save_current_file` is set to true, so you can format the code before running by enabling format on save (see [none-ls wiki](https://github.com/nvimtools/none-ls.nvim/wiki/Formatting-on-save)).

> But I think maybe `user event` is still a useful function

It could be, but I can't see any useful use-case for it right now. If anyone comes up with good ideas involving the usage of this feature then we'll consider implementing it, maybe as an autocommand.

**Comment by XXiaoA** [comment]
Thanks, it is clear!
