### ISSUE TITLE
Issue with nui.nvim when recieving contest problems

### ISSUE THREAD

**Issue by ammar1510** [xeluxee/competitest.nvim#55]
## Versions
1. NeoVim: v0.9.5
2. competitest: [c3cb0e2](https://github.com/xeluxee/competitest.nvim/commit/c3cb0e2b0916a879c4d3dcb5737e6c046dd0afc5)- latest
3. nui.nvim: [274fa89](https://github.com/MunifTanjim/nui.nvim/commit/274fa89a9b4bed746647c2917091902f882509ec) - latest
4. Terminal - Alacritty v0.13.2
## Error message
<img width="1343" alt="Screenshot 2024-05-04 at 9 28 16 PM" src="https://github.com/xeluxee/competitest.nvim/assets/70856548/00342d21-c770-4e0f-87ce-ab64d0968ec0">

## Reproducible steps:
in normal mode
1. :Competitest receive contest
2.    <kbd>return</kbd>

**Comment by xeluxee** [comment]
Can't reproduce with `nui.nvim` latest version.
Is this issue still relevant?
