### ISSUE TITLE
When there exists another solution file created before, the default behavior should not be 'overwrite the old file' but 'keep the old file'

### ISSUE THREAD

**Issue by ShelpAm** [xeluxee/competitest.nvim#56]
If people choose to press `esc` or by accident, they probably want to keep the old file but not to overwrite them.

**Comment by xeluxee** [comment]
Are you talking about receiving testcases? Please provide steps to reproduce.

**Comment by ShelpAm** [comment]
> Are you talking about receiving testcases? Please provide steps to reproduce.

I am talking about receiving problems. When receiving existing problems, and we press "Esc", my original solution file is overwritten.

**Comment by xeluxee** [comment]
Fixed with 4ef440c20eec0be407f455f5db4bfad4acb2641e.
