### ISSUE TITLE
Uncorrectly parsing problems containing slashes

### ISSUE THREAD

**Issue by SeifKaroui** [xeluxee/competitest.nvim#57]
Example:  [Educational Codeforces Round 166 Rated for Div2](https://codeforces.com/contest/1976) 

After receiving the contest, problem B is not parsed correctly as it contains slashes in its name:

![image](https://github.com/xeluxee/competitest.nvim/assets/21332330/32bdd7a1-c304-490d-8996-e7522e35032e)
![image](https://github.com/xeluxee/competitest.nvim/assets/21332330/590880ba-deb9-41f8-b4ea-26df61d6ce76)

**Comment by SeifKaroui** [comment]
@beka-birhanu  I couldn't pull this specific commit due to these errors:
![image](https://github.com/user-attachments/assets/30ba458a-25a7-4d7c-9b8a-6c959b29dd77)
![image](https://github.com/user-attachments/assets/a3ac9c3a-b6c2-42d4-bcaf-086cd6717544)

**Comment by beka-birhanu** [comment]
@SeifKaroui I think it is because the PR is not merged yet.

**Comment by SeifKaroui** [comment]
@beka-birhanu it is working now. Thanks a lot.

**Comment by xeluxee** [comment]
Solved with 3aa0bdac56628f807050b05e8641a182578466aa.
