### ISSUE TITLE
Input, Output, and Expected Output not showing

### ISSUE THREAD

**Issue by rohmanhakim** [xeluxee/competitest.nvim#61]
Hi, i installed competitest with the following setup:

1. my `init.nvim`:
```
call plug#begin()

Plug 'MunifTanjim/nui.nvim'
Plug 'xeluxee/competitest.nvim'

call plug#end()

lua << EOF
require('competitest').setup {}
EOF
```

2. Here is the testcases i use:
![image](https://github.com/user-attachments/assets/828d74d6-e704-4f84-9dd7-a86ea09def81)
![image](https://github.com/user-attachments/assets/7412edbc-eb18-4153-a326-5d8991e3317f)
![image](https://github.com/user-attachments/assets/9d8884fa-734f-4577-9c05-1ef70b95dcf1)
![image](https://github.com/user-attachments/assets/e76728eb-7509-47d7-98ca-0b2ec403a8df)
![image](https://github.com/user-attachments/assets/3abcd935-746b-4650-b3b4-25704648ddc8)
![image](https://github.com/user-attachments/assets/14fda03a-d741-46ea-83c0-cf08dccc7172)
![image](https://github.com/user-attachments/assets/6c62f638-0469-4a82-9a26-f3b91059b23f)

3. Here is the UI that shows in my nvim:
![image](https://github.com/user-attachments/assets/5a549d43-1bfd-4637-a2af-64d06bc1e058)

As you can see, all testcases and the actual output are not showing in the runner UI. Kindly help where did i do wrong in my setup. 

Thank you

**Comment by xeluxee** [comment]
This may be a colorscheme issue. What colorscheme are you using? What happens if you change colorscheme?

**Comment by xeluxee** [comment]
Just noticed that the cursor in the screenshot is on `Compile`. You should move it to a testcase line to view its content.
