### ISSUE TITLE
How about changing filename to ignore periods (.) and replace spaces with undersore?

### ISSUE THREAD

**Issue by asibhossen897** [xeluxee/competitest.nvim#64]
Currently the filenames when fetching from a problem is like `N. Char.cpp`
![image](https://github.com/user-attachments/assets/0ad78c8c-114f-4674-b991-a624abf107a8)
Then we'd have to rename it again. **It'd be much better if it would be like `N_Char.cpp` this.**

**Comment by xeluxee** [comment]
https://github.com/xeluxee/competitest.nvim/pull/65#issuecomment-2422663527
