### ISSUE TITLE
if path contain special character like '#', edit command report error

### ISSUE THREAD

**Issue by qixiao986** [xeluxee/competitest.nvim#67]
recently I participate this [contest:](https://atcoder.jp/contests/abc379), contest name has '#', competitest.nvim receive problem show error: `Error executing vim.schedule lua callback: .../nvim/lazy/competitest.nvim/lua/competitest/commands.lua:342: Vim(edit):E194: No alternate file name to substitute for '#': edit /contests/AtCoder/Toyota Programming Contest 2024#11（AtCoder Beginner Contest 379）/D - Home Garden.cpp
stack traceback:
	[C]: in function 'nvim_command'
	.../nvim/lazy/competitest.nvim/lua/competitest/commands.lua:342: in function 'callback'
	...e/nvim/lazy/competitest.nvim/lua/competitest/widgets.lua:286: in function 'on_submit'
	...o/.local/share/nvim/lazy/nui.nvim/lua/nui/input/init.lua:162: in function <...o/.local/share/nvim/lazy/nui.nvim/lua/nui/input/init.lua:149>
"`
https://github.com/xeluxee/competitest.nvim/blob/20ce9ba1b2f7502291a23ad06096e6650917f0c2/lua/competitest/commands.lua#L342

**Comment by xeluxee** [comment]
Fixed with e397635.
