### ISSUE TITLE
I can't get my template_file to load.

### ISSUE THREAD

**Issue by insomnia-creator** [xeluxee/competitest.nvim#68]
Eg. I went to codeforces, opened a problem, ran `:Competitest receive problem`, and expect a template_file to come up. It receives all test cases properly. But I can't get my template file to load.

My configuration:

```lua
require('competitest').setup {
  compile_command = {
    cpp = {
      exec = "g++",
      args = {'-std=c++20','$(FNAME)', '-o', '$(FNOEXT)'}
    },
    run_command = {
      cpp       = { exec = './$(FNOEXT)' }
    },
    evaluate_template_modifiers = false,
    template_file ="~/Projets/competitive/template.cpp"
  }
}
```

I am not sure how you can reproduce this issue, I'm willing to provide more information. 

This is my template file, very simple
```cpp
   1   │ #include <bits/stdc++.h>
   2   │ using namespace std;
   3   │ using ll = long long;
   4   │ template <typename T> using vv = vector<vector<T>>;
   5   │ template <typename T> using v = vector<vector<T>>;
   6   │ const int mod = 1e9 + 7;
   7   │
   8   │ int main() {
   9   │   int t;
  10   │   return 0;
  11   │ }
```

Note the line numbers are just from running `cat` aliased to `bat` i think.

**Comment by xeluxee** [comment]
Your configuration looks correct. Maybe the word `Projets` in `template_file` path is a typo.

**Comment by insomnia-creator** [comment]
It isn't. It's french.

**Comment by insomnia-creator** [comment]
Fixed by specifying literal path.
